env:
  global:
    - GCP_PROJECT_ID=pgr301-exam-295320
    - tf_version=0.13.5
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
branches:
  only:
    - master
before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in gkey.json.enc -out gkey.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source "$HOME/google-cloud-sdk/path.bash.inc"
  - gcloud auth activate-service-account --key-file=gkey.json
  - gcloud config set project "${GCP_PROJECT_ID}"
  - export GOOGLE_APPLICATION_CREDENTIALS=./gkey.json
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip
install: true
script:
  - |-
    set -ex;
    export TF_VAR_logz_token=$(gcloud secrets versions access latest --secret=logz_token)
    export TF_VAR_db_username=$(gcloud secrets versions access latest --secret=db_username)
    export TF_VAR_db_password=$(gcloud secrets versions access latest --secret=db_password)
    terraform init
    terraform plan
    terraform apply --auto-approve
    terraform output